import { Poppins } from "next/font/google";
import "./globals.css";
import UserContextProvider from "./context/UserContextProvider";
const poppins = Poppins({subsets:["latin"],weight:"600"});

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={poppins.className}>
        <UserContextProvider>
        {children}
        </UserContextProvider>
        </body>
    </html>
  );
}
